[tool.black]
line-length = 120

[tool.pylint.messages_control]
disable = "R,attribute-defined-outside-init,bad-option-value,invalid-name,locally-disabled,missing-docstring,ungrouped-imports,wrong-import-order,wrong-import-position,broad-except,len-as-condition,bad-continuation,too-many-lines,unsubscriptable-object,inherit-non-class"

[tool.pylint.reports]
reports = "no"
score = "no"
output-format = "parseable"

[tool.pylint.format]
max-line-length=120

[tool.isort]
combine_as_imports = true
line_length = 120
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
default_section = "THIRDPARTY"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
