name: scheduled-run

on:
  schedule:
    # UTC time
    - cron: "0 6,16 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute python script
      env:
        ETHSCAN_API_KEY: ${{ secrets.ETHSCAN_API_KEY }}
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        TELEGRAM_CGROUP_TOKEN: ${{ secrets.TELEGRAM_CGROUP_TOKEN }}
        TELEGRAM_CGROUP_CHAT_ID: ${{ secrets.TELEGRAM_CGROUP_CHAT_ID }}
      run: |
        python cci.py cci -r
        python cci.py cgroup

